model:
  model_name: gpt-oss-120b
  tokenizer_path: bert-base-uncased

data:
  original_dataset_size: 246
  batch_size: 246
  num_batches: 1
  take_subset: false
  subset_size: null
  output_path: json_data/entity_discovery_output

printout: true